### ISSUE TITLE
usage of `async` 3.7 incompatible in kernel.py

### ISSUE THREAD

**Issue by KittenHero** [Calysto/matlab_kernel#111]

**Comment by blink1073** [comment]
Hi @KittenHero, do you have a full traceback?

**Comment by blink1073** [comment]
I suspect it is this line: https://github.com/Calysto/matlab_kernel/blob/616c495aac2628ef095ede71f039eafdfc4eb9f5/matlab_kernel/kernel.py#L248

**Comment by KittenHero** [comment]
yep it's that line :+1:

**Comment by blink1073** [comment]
Hmm, that line is part of the Mathworks `matlab.engine` API.  Can you please post the issue to them?  https://www.mathworks.com/help/matlab/apiref/matlab.engine.matlabengine-class.html

**Comment by KittenHero** [comment]
I'm not sure how to report a bug to them, but a work around could be

```
future = self._matlab.eval(code, **{ 'nargout': 0, 'async': True})
```

**Comment by blink1073** [comment]
Hmm, we could wrap that in an `if PY2`.  Let me try that

**Comment by blink1073** [comment]
Wait, it that a syntax error in py 3.7?

**Comment by blink1073** [comment]
Ugh, not thinking straight, just got done running.

**Comment by blink1073** [comment]
Okay, it is a syntax error in Python 3.7.  Given that their own page says "The engine supports the reference implementation (CPython) for Python versions 2.7, 3.5, and 3.6", I'm inclined to match that compatibility list.

**Comment by KittenHero** [comment]
fair enough

**Comment by blink1073** [comment]
Thanks for the report though!

**Comment by leeweizhe1993** [comment]
I think I meet the same error
![image](https://user-images.githubusercontent.com/32242263/48816395-f8298b80-ed7c-11e8-844e-6ba52c515f70.png)

[I 10:56:47.677 LabApp] Kernel started: ca33a3a5-c284-41ca-a8c1-e4c2062f684e
Traceback (most recent call last):
  File "/Users/lee_excited/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/lee_excited/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/lee_excited/miniconda3/lib/python3.7/site-packages/matlab_kernel/__main__.py", line 2, in <module>
    from .kernel import MatlabKernel
  File "/Users/lee_excited/miniconda3/lib/python3.7/site-packages/matlab_kernel/kernel.py", line 250
    future = self._matlab.eval(code, nargout=0, async=True)

**Comment by adityam** [comment]
Is there a suggested workaround this error?

**Comment by blink1073** [comment]
For now, using one of the supported Python versions: https://www.mathworks.com/help/matlab/matlab-engine-for-python.html

**Comment by bjoseru** [comment]
I just installed MATLAB R2019a and ran into the same issue. It seems the new MATLAB release officially supports Python 3.7. I am using Anaconda's python, which is 3.7.1 at time of writing. I am not sure though it is a CPython. 

I can confirm though, that @KittenHero 's workaround worked for me. I simply edited the relevant line in `~/anaconda3/lib/python3.7/site-packages/matlab_kernel/kernel.py` and then subsequent `python -m matlab_kernel install --user` ran through without error.

**Comment by blink1073** [comment]
Not sure why I didn't think of this before.   Can someone please confirm whether the following works on both Python 2 and Python 3 by changing `kernel.py`?

```python
kwargs = {'nargout': 0, 'async': True }
future = self._matlab.eval(code, **kwargs) 
```

**Comment by bjoseru** [comment]
I can confirm it works for me on anaconda python 2.7.16 and anaconda python 3.7.1. Thanks for the quick fix!

**Comment by blink1073** [comment]
Fixed in the 0.16.2 release.

**Comment by dar10p** [comment]
Sorry to bother you, I reinstalled everything from Anaconda, with Python 3.7, to every kernel I needed. For Matlab I downloaded this release and the problem persists. Line still reads

` future = self._matlab.eval(code, nargout=0, async=True) `

Replaced it there by `future = self._matlab.eval(code, **{ 'nargout': 0, 'async': True})`. Don't know why it was unaffected by the changes you did.

**Comment by blink1073** [comment]
What does `python -c "import matlab_kernel; print(matlab_kernel.__version__)"` show?

**Comment by dar10p** [comment]
It shows “0.16.2"

> On Apr 23, 2019, at 22:43, Steven Silvester <notifications@github.com> wrote:
> 
> python -c "import matlab_kernel; print(matlab_kernel.__version__)"

--
____________________________________________________________
Dario Gabriel Perez - Physicist, PhD (UNLP)
Profesor Titular - Full Professor
Instituto de Física, Pontificia Universidad Católica de Valparaíso (PUCV)
Av. Universidad 330, Campus Curauma,
234-0000 Valparaíso, Chile.
Office: +56 32 2 27 4892/4884
